package com.jmr.stream.demostream.model.entity;


import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import java.time.LocalDateTime;

/**
 * Events to be record by App
 */

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Builder
public class EventEntity {

    /**
     * Id
     * Autogenerated value
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    /**
     * Creation date
     * Format should be ISO DATE TIME
     * Default builder value
     */
    @CreatedDate
    @Basic
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
    @Builder.Default
    private LocalDateTime creationDate = LocalDateTime.now();

    private String type;

    /**
     * Comments
     * Define type as text, comments can be really long
     */
    @Column(columnDefinition = "TEXT")
    private String comment;

    /**
     * Requester user code
     */
    private String requestedBy;

}
